version: "3.1"

services:
  api-service:
    container_name: medicine_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/medicine/log/:/var/medicine/log/
    ports:
      - "8081:8081"
