version: "3.1"
services:
  web:
    container_name: medicine_fonter
    image: nginx
    ports:
      - 80:80
    volumes:
      - /opt/application/docker/nginx/dist:/usr/share/nginx/html
      - /opt/application/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/application/docker/nginx//conf.d:/etc/nginx/conf.d
      - /opt/application/docker/nginx/log:/var/log/nginx
      - /etc/localtime:/etc/localtime
    restart: always
